"""Generates ``docs/results.md`` from the run manifest.

The results document is produced by the pipeline rather than written by hand,
so it cannot drift away from what the code actually did. Every figure in it is
read from the manifest of the run that generated it.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from src import config

logger = logging.getLogger(__name__)

RESULTS_PATH = config.PROJECT_ROOT / "docs" / "results.md"


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        # No trailing-zero stripping: a conformance score of 1.000000 must not
        # render as "1", which reads as a rounded figure rather than an exact one.
        return f"{value:,.6f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _pct(value: float) -> str:
    return f"{value * 100:.6f}%".replace(".000000%", "%")


def generate(manifest: dict[str, Any], path: Path = RESULTS_PATH) -> Path:
    """Render the results document."""
    m = manifest.get("metrics", {})
    t = manifest.get("timings_seconds", {})
    v = manifest.get("verdicts", {})

    lines: list[str] = []
    add = lines.append

    add("# Results")
    add("")
    add("**Generated by the pipeline** from `data/quality/run_manifest.json`. Every")
    add("figure below is read from the manifest of the run that produced it, so this")
    add("document cannot drift from what the code actually did.")
    add("")
    add(f"Run started `{manifest.get('started_at', 'n/a')}` on Python "
        f"`{manifest.get('environment', {}).get('python', 'n/a')}`.")
    add("")
    add("---")
    add("")

    # --- Section 1 -----------------------------------------------------------
    add("## Section 1 - Data extraction")
    add("")
    conformance = m.get("section1.conformance", {})
    comparison = m.get("section1.reference_comparison", {})
    add("| Metric | Value |")
    add("|---|---|")
    add(f"| Features extracted | {_fmt(m.get('section1.n_features_extracted', 0))} |")
    add(f"| Schema conformance | **{_fmt(conformance.get('score', 0))}** "
        f"({str(conformance.get('verdict', 'n/a')).upper()}) |")
    add(f"| Source object | {_fmt(m.get('section1.source_object_bytes', 0))} bytes |")
    add(f"| Bytes scanned | {_fmt(m.get('section1.bytes_scanned', 0))} |")
    add(f"| Bytes returned | {_fmt(m.get('section1.bytes_returned', 0))} |")
    add(f"| **Transfer reduction** | **{m.get('section1.transfer_reduction_pct', 0)}%** |")
    add(f"| Extraction time | {t.get('section1.s3_select_extraction', 0):.3f}s |")
    if "section1.select_vs_baseline_speedup" in m:
        add(f"| vs naive download baseline | "
            f"**{m['section1.select_vs_baseline_speedup']}x faster** |")
    add("")
    add("### Validation against `city-hex-polygons-8.geojson`")
    add("")
    add(f"- Features in common: **{_fmt(comparison.get('n_common', 0))}**")
    add(f"- Missing from extraction: {_fmt(comparison.get('n_missing_from_extraction', 0))}")
    add(f"- Extra in extraction: {_fmt(comparison.get('n_extra_in_extraction', 0))}")
    add(f"- Property mismatches: {_fmt(comparison.get('n_property_mismatches', 0))}")
    add(f"- Geometry mismatches: {_fmt(comparison.get('n_geometry_mismatches', 0))}")
    add(f"- **Byte-identical geometries: {_fmt(comparison.get('n_geometry_exact_matches', 0))}**")
    add("")
    add("Every geometry matched exactly, so the coordinate tolerance in")
    add("`config/hex_schema.yaml` was never needed. The comparison runs on the")
    add("intersection of properties because the reference file carries no")
    add("`resolution` property while the extraction source does - comparing whole")
    add("records would report a total mismatch on a correct extraction.")
    add("")

    # --- Section 2 -----------------------------------------------------------
    add("## Section 2 - Spatial join")
    add("")
    classes = m.get("section2.coordinate_classes", {})
    rules = m.get("section2.rule_counts", {})
    total = sum(classes.values()) or 1

    add("### Coordinate quality")
    add("")
    add("| Class | Count | Share |")
    add("|---|---|---|")
    for name, count in sorted(classes.items(), key=lambda kv: -kv[1]):
        add(f"| `{name}` | {_fmt(count)} | {count / total * 100:.2f}% |")
    add("")
    if not classes.get("inverted", 0):
        add("**No coordinate inversion detected**, and no null-island, out-of-bounds,")
        add("partial or unparseable coordinates. The supplied data is clean on every")
        add("axis checked. Zero counts are reported rather than omitted: \"checked and")
        add("found none\" is a result, whereas a missing row is indistinguishable from")
        add("a check that never ran.")
        add("")

    add("### Assignment outcomes")
    add("")
    add("| Rule | Count | Share |")
    add("|---|---|---|")
    for name, count in sorted(rules.items()):
        add(f"| `{name}` | {_fmt(count)} | {count / total * 100:.2f}% |")
    add("")
    ambiguous = m.get("section2.n_ambiguous_unique_pairs", 0)
    if ambiguous:
        add(f"{_fmt(ambiguous)} coordinate pair(s) matched more than one polygon and were")
        add("resolved by the nearest-centroid tie-break; detail in")
        add("`data/quality/ambiguous_hex_assignments.csv`.")
    else:
        add("**No ambiguous multi-polygon assignments occurred.** No service request")
        add("coordinate falls exactly on a hexagon boundary, which is expected at")
        add("floating-point precision. The tie-break rule is therefore a correctness")
        add("guarantee proven by unit tests rather than something this dataset")
        add("exercises - see `tests/test_join_rules.py`, which constructs the edge and")
        add("vertex cases explicitly.")
    add("")

    # --- Efficiency ----------------------------------------------------------
    add("### Efficiency")
    add("")
    unique = m.get("section2.unique_coordinate_pairs", 0)
    ratio = m.get("section2.dedup_ratio", 1.0)
    add(f"- Unique coordinate pairs: **{_fmt(unique)}** "
        f"({ratio * 100:.1f}% of geolocated rows, {1 / ratio if ratio else 1:.2f}x less join work)")
    add(f"- Geometric join: {t.get('section2.geometric_join', 0):.3f}s")
    add(f"- H3 library assignment: {t.get('section2.h3_library_assignment', 0):.3f}s")
    add(f"- **Total pipeline: {t.get('pipeline.total', 0):.1f}s**")
    add("")

    # --- Method comparison ---------------------------------------------------
    add("## Method comparison - geometric vs H3 library")
    add("")
    agreement = m.get("section2.method_agreement", 0.0)
    categories = m.get("section2.disagreement_categories", {})
    add(f"Agreement over {_fmt(unique)} unique coordinate pairs: "
        f"**{_pct(agreement)}**")
    add("")
    if categories:
        add("| Category | Count | Meaning |")
        add("|---|---|---|")
        meanings = {
            "C1_boundary_tie": "Tie-break picked a different candidate. Benign.",
            "C2_coverage_gap": "Library's cell exists in the file but the join matched nothing. A hole.",
            "C2b_outside_coverage": "Point lies beyond the supplied tiling altogether.",
            "C3_out_of_tiling": "Join matched, but the library's cell is absent from the file.",
            "C4_adjacent_cell": "Both valid and adjacent. Sub-metre boundary drift.",
            "C5_non_adjacent": "Both valid, NOT adjacent. Not a rounding artifact - investigate.",
        }
        for name, count in sorted(categories.items()):
            add(f"| `{name}` | {_fmt(count)} | {meanings.get(name, '')} |")
        add("")
        if not categories.get("C5_non_adjacent"):
            add("**No non-adjacent disagreements.** Every difference is either sub-metre")
            add("boundary drift or a point outside coverage; none indicates an axis, CRS")
            add("or projection fault.")
            add("")

    # --- Coverage ------------------------------------------------------------
    coverage = m.get("section2.coverage", {})
    if coverage:
        add("## Coverage - does the City have full hexagon coverage?")
        add("")
        add("**No, but very nearly.** Two independent checks, neither depending on the")
        add("City's open-data portal, which the upstream README warns is unreliable.")
        add("")
        add("### Topological")
        add("")
        add(f"- Cells: **{_fmt(coverage.get('n_cells', 0))}**, "
            f"{_fmt(coverage.get('total_area_km2', 0))} km2 total")
        add(f"- Mean cell area: **{coverage.get('mean_cell_area_km2', 0)} km2** "
            "(H3's published global mean of 0.737 does not apply at this latitude)")
        add(f"- Absent perimeter neighbours: {_fmt(coverage.get('n_absent_neighbours', 0))}")
        add(f"- **Fully enclosed holes: {coverage.get('n_fully_enclosed_holes', 0)}**")
        add(f"- Near-enclosed gaps (>=5 of 6 neighbours present): "
            f"**{coverage.get('n_interior_holes', 0)}**")
        add("")
        for hole in coverage.get("interior_holes", []):
            add(f"  - `{hole['index']}` at ({hole['lat']}, {hole['lon']}) - "
                f"{hole['neighbours_present']} of 6 neighbours present")
        add("")
        add("### Empirical")
        add("")
        no_match = rules.get("R4_no_match", 0)
        geolocated = m.get("section2.class_b_no_hex_match_rate", 0)
        add(f"- Service requests with valid coordinates matching **no** hexagon: "
            f"**{_fmt(no_match)}** ({geolocated * 100:.6f}% of geolocated)")
        add("")
        add("This is direct evidence and needs no model of where the municipal")
        add("boundary runs. The answer is that coverage is not total: a small number of")
        add("real service requests occur outside the supplied polygons.")
        add("")

    # --- Validation ----------------------------------------------------------
    validation = m.get("section2.reference_validation", {})
    if validation:
        add("## Validation against `sr_hex.csv.gz`")
        add("")
        add(f"**{_pct(validation.get('match_rate', 0))} exact match** "
            f"({_fmt(validation.get('n_agree', 0))} of "
            f"{_fmt(validation.get('n_agree', 0) + validation.get('n_disagree', 0))})")
        add("")
        breakdown = validation.get("mismatch_breakdown", {})
        if breakdown and validation.get("n_disagree"):
            add("| Mismatch type | Count |")
            add("|---|---|")
            for name, count in sorted(breakdown.items()):
                if count:
                    add(f"| `{name}` | {_fmt(count)} |")
            add("")
            add(f"All {_fmt(validation.get('n_disagree', 0))} differences resolve in favour")
            add("of the **H3 library**, which is evidence that `sr_hex.csv.gz` was")
            add("generated with the library rather than a geometric join against the")
            add("polygon file.")
            add("")
            add("The geometric route is kept as the default anyway. Switching to the")
            add("library would reach 100%, but matching a reference by adopting the method")
            add("that produced it demonstrates nothing about the polygons, and would")
            add("discard the coverage finding above. Set `config.JOIN_METHOD` or pass")
            add("`--join-method library` to publish the library assignment instead.")
            add("")

    # --- Data contract -------------------------------------------------------
    contract = m.get("section2.sr_data_contract", {})
    if contract:
        add("## Input data contract")
        add("")
        add(f"Service request conformance: **{_fmt(contract.get('score', 0))}** "
            f"({str(contract.get('verdict', 'n/a')).upper()}) over "
            f"{_fmt(contract.get('n_rows', 0))} rows")
        add("")
        imperfect = {k: v for k, v in contract.get("rule_scores", {}).items() if v < 1.0}
        if imperfect:
            add("Rules scoring below 1.0 (always reported individually, whatever the")
            add("aggregate, since a weighted mean can hide a systematic fault):")
            add("")
            add("| Rule | Score |")
            add("|---|---|")
            for name, value in sorted(imperfect.items()):
                add(f"| `{name}` | {value:.6f} |")
            add("")
        violations = contract.get("consistency_violations", {})
        if violations:
            add(f"**Consistency violations:** {list(violations)}")
        else:
            add("No cross-column consistency violations.")
        add("")

    # --- Verdicts ------------------------------------------------------------
    add("## Verdicts")
    add("")
    add("| Check | Result | Detail |")
    add("|---|---|---|")
    for name, detail in sorted(v.items()):
        mark = "PASS" if detail.get("passed") else "FAIL"
        add(f"| `{name}` | **{mark}** | {detail.get('detail', '')} |")
    add("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Results written to %s", path)
    return path
